CycleProductionBuildings: TAB Ctrl
	Description: 下一个建筑
	Types: Production
	Contexts: Player, Spectator

SelectProductionBuilding: TAB
	Description: 当前建筑
	Types: Production
	Contexts: Player

Production01: F1
	Description: 排程 01
	Types: ProductionSlot
	Contexts: Player

Production02: F2
	Description: 排程 02
	Types: ProductionSlot
	Contexts: Player

Production03: F3
	Description: 排程 03
	Types: ProductionSlot
	Contexts: Player

Production04: F4
	Description: 排程 04
	Types: ProductionSlot
	Contexts: Player

Production05: F5
	Description: 排程 05
	Types: ProductionSlot
	Contexts: Player

Production06: F6
	Description: 排程 06
	Types: ProductionSlot
	Contexts: Player

Production07: F7
	Description: 排程 07
	Types: ProductionSlot
	Contexts: Player

Production08: F8
	Description: 排程 08
	Types: ProductionSlot
	Contexts: Player

Production09: F9
	Description: 排程 09
	Types: ProductionSlot
	Contexts: Player

Production10: F10
	Description: 排程 10
	Types: ProductionSlot
	Contexts: Player

Production11: F11
	Description: 排程 11
	Types: ProductionSlot
	Contexts: Player

Production12: F12
	Description: 排程 12
	Types: ProductionSlot
	Contexts: Player

Production13: F1 CTRL
	Description: 排程 13
	Types: ProductionSlot
	Contexts: Player

Production14: F2 CTRL
	Description: 排程 14
	Types: ProductionSlot
	Contexts: Player

Production15: F3 CTRL
	Description: 排程 15
	Types: ProductionSlot
	Contexts: Player

Production16: F4 CTRL
	Description: 排程 16
	Types: ProductionSlot
	Contexts: Player

Production17: F5 CTRL
	Description: 排程 17
	Types: ProductionSlot
	Contexts: Player

Production18: F6 CTRL
	Description: 排程 18
	Types: ProductionSlot
	Contexts: Player

Production19: F7 CTRL
	Description: 排程 19
	Types: ProductionSlot
	Contexts: Player

Production20: F8 CTRL
	Description: 排程 20
	Types: ProductionSlot
	Contexts: Player

Production21: F9 CTRL
	Description: 排程 21
	Types: ProductionSlot
	Contexts: Player

Production22: F10 CTRL
	Description: 排程 22
	Types: ProductionSlot
	Contexts: Player

Production23: F11 CTRL
	Description: 排程 23
	Types: ProductionSlot
	Contexts: Player

Production24: F12 CTRL
	Description: 排程 24
	Types: ProductionSlot
	Contexts: Player
